import { createClient, type SupabaseClient } from 'jsr:@supabase/supabase-js@2';
import { getCorsHeaders } from '../_shared/cors.ts';
import { checkRateLimit } from '../_shared/rateLimit.ts';
import { requireSubscription } from '../_shared/requireSubscription.ts';
import {
  buildLocalProfileOrNullPostgrestFilter,
  isValidLocalProfileId,
} from '../_shared/localProfileId.ts';
import {
  type JsonRecord,
  parsePullPreferenceRow,
  PreferenceInfrastructureError,
  PreferenceValidationError,
  requireKnownKeys,
  requirePostgresString,
  requireRecord,
  returnedAuthStatus,
  safeErrorName,
} from '../_shared/profilePreferenceContract.ts';

// UUID validation regex for entity ids.
// Sessions, routines, and cycles are generated by the client via generateUUID().
// Badges and personal records use portal UUIDs when the client has them; older
// mobile builds may still send local integer IDs, which are ignored for parity.
// For profile ids use isValidLocalProfileId — the "default" sentinel is legal there.
const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Mobile Sync Pull — returns portal data modified since the client's last sync.
 *
 * POST /functions/v1/mobile-sync-pull
 * Authorization: Bearer <GoTrue JWT>
 * Body: {
 *   deviceId: string,
 *   lastSync?: number,
 *   profileId?: string,
 *   cursor?: string,          // Optional: pagination cursor from previous response
 *   pageSize?: number,        // Optional: entities per page (default 75, max 300)
 *   knownEntityIds?: {        // Optional: parity-based sync (new)
 *     sessionIds?: string[],
 *     routineIds?: string[],
 *     cycleIds?: string[],
 *     badgeIds?: string[],
 *     personalRecordIds?: string[]
 *   }
 * }
 *
 * Sync Modes:
 *   - Parity mode (new): client sends knownEntityIds → server returns entities NOT in those lists
 *   - Timestamp mode (legacy): client sends lastSync → server returns entities modified since
 *   - Full sync: neither provided → server returns all entities
 *
 * Pagination:
 *   - When cursor is absent, starts from the beginning
 *   - When cursor is present, resumes from that position
 *   - Entity types are paged in order: sessions → routines → cycles → badges → stats → customExercises
 *   - Response includes nextCursor and hasMore for client to loop
 *   - Client should loop until hasMore: false before updating lastSyncTimestamp
 *
 * Backward Compatibility:
 *   - cursor and pageSize are optional with sensible defaults
 *   - Existing clients without pagination continue to work
 *   - lastSync still supported for timestamp-based filtering
 *
 * Returns:
 *   {
 *     syncTime: number,
 *     nextCursor?: string,  // Present if hasMore is true
 *     hasMore: boolean,     // True if more pages remain
 *     sessions: [...],      // Nested: exercises → sets → repSummaries
 *     routines: [...],      // Nested: exercises
 *     cycles: [...],        // Nested: days
 *     personalRecords: [...],
 *     rpgAttributes: {...} | null,
 *     badges: [...],
 *     gamificationStats: {...} | null,
 *     localProfiles: [...],
 *     externalActivities: [...],
 *     customExercises: [...]
 *   }
 */

interface PullRequest {
  deviceId: string;
  /** @deprecated Use knownEntityIds for parity-based sync */
  lastSync?: number;
  profileId?: string;
  /** Optional cursor for pagination. If absent, starts from beginning. */
  cursor?: string;
  /** Optional page size. Defaults to 75. */
  pageSize?: number;
  /** Entity IDs client already has. Server returns entities NOT in these lists. */
  knownEntityIds?: {
    sessionIds?: string[];
    routineIds?: string[];
    cycleIds?: string[];
    badgeIds?: unknown[];
    personalRecordIds?: unknown[];
  };
}

function uuidParityIds(ids: unknown[] | undefined): string[] {
  return (ids ?? []).filter((id): id is string => typeof id === 'string' && UUID_REGEX.test(id));
}

/**
 * Build a retryable 503 response for a failed Supabase read. Sync pulls must
 * never return partial success: if a required child/entity read fails the
 * client could advance its sync state and silently lose the missing rows, so
 * we fail the whole pull and let the client retry.
 */
function readFailure(
  entity: string,
  error: { code?: string; message?: string; hint?: string },
  cors: Record<string, string>,
): Response {
  console.error(`Error fetching ${entity}:`, error);
  return new Response(
    JSON.stringify({
      error: `Failed to fetch ${entity}`,
      code: error.code ?? 'UNKNOWN',
      details: error.message ?? error.hint ?? null,
    }),
    { status: 503, headers: { ...cors, 'Content-Type': 'application/json', 'Retry-After': '5' } },
  );
}

/**
 * Determines if the request uses parity-based sync (new) or timestamp-based (legacy).
 * Parity mode is used when knownEntityIds is provided.
 */
function isParityMode(body: PullRequest): boolean {
  return !!body.knownEntityIds;
}

// ─── Pagination Configuration ───────────────────────────────────────

const DEFAULT_PAGE_SIZE = 75;
const MAX_PAGE_SIZE = 300;

/**
 * Maximum number of entity IDs the client may include in a single parity-based
 * pull request.
 *
 * UPDATE 2026-04-20: Now using RPC functions (get_sessions_excluding_ids, etc.)
 * which accept IDs in POST body instead of URL params. No more URL length limit.
 * Raised cap to 10,000 for power users with years of workout history.
 *
 * The RPC functions use PostgreSQL array parameters, which handle large arrays
 * efficiently via `id != ALL(p_known_ids)`.
 */
const MAX_PARITY_IDS = 10_000;

// Entity types in pagination order
type EntityType = 'sessions' | 'routines' | 'cycles' | 'badges' | 'stats' | 'personalRecords' | 'customExercises';
const ENTITY_ORDER: EntityType[] = ['sessions', 'routines', 'cycles', 'badges', 'stats', 'personalRecords', 'customExercises'];

interface DecodedCursor {
  type: EntityType;
  updatedAt: number; // epoch ms
  id: string;
}

/**
 * Encodes pagination state into an opaque cursor string.
 * Format: base64(JSON({type, updatedAt, id}))
 */
function encodeCursor(type: EntityType, updatedAt: number, id: string): string {
  const payload = JSON.stringify({ type, updatedAt, id });
  // Use btoa for base64 encoding (available in Deno)
  return btoa(payload);
}

/**
 * Decodes a cursor string back to pagination state.
 * Returns null if cursor is invalid or malformed.
 */
function decodeCursor(cursor: string): DecodedCursor | null {
  try {
    const decoded = atob(cursor);
    const parsed = JSON.parse(decoded);
    // Validate structure
    if (
      typeof parsed.type !== 'string' ||
      !ENTITY_ORDER.includes(parsed.type as EntityType) ||
      typeof parsed.updatedAt !== 'number' ||
      !Number.isFinite(parsed.updatedAt) ||
      typeof parsed.id !== 'string'
    ) {
      return null;
    }
    try {
      new Date(parsed.updatedAt).toISOString();
    } catch {
      return null;
    }
    // Most paged entity ids are UUIDs. Custom exercise ids are mobile-minted
    // catalog ids and may be stable non-UUID strings.
    if (parsed.type === 'customExercises') {
      if (parsed.id.length === 0) {
        return null;
      }
    } else if (!UUID_REGEX.test(parsed.id)) {
      return null;
    }
    return parsed as DecodedCursor;
  } catch {
    return null;
  }
}

const PULL_BODY_KEYS = new Set([
  'deviceId',
  'lastSync',
  'profileId',
  'cursor',
  'pageSize',
  'knownEntityIds',
]);

const KNOWN_ENTITY_ID_KEYS = new Set([
  'sessionIds',
  'routineIds',
  'cycleIds',
  'badgeIds',
  'personalRecordIds',
]);

class PullRequestParseFailure extends Error {
  constructor(
    readonly status: 400 | 413,
    readonly body: JsonRecord,
  ) {
    super('Invalid mobile sync pull request');
    this.name = 'PullRequestParseFailure';
  }
}

interface ParsedPullRequest {
  body: PullRequest;
  profileId: string | null;
  lastSyncISO: string;
  pageSize: number;
  cursor: DecodedCursor | null;
}

const invalidPullRequest = (): never => {
  throw new PullRequestParseFailure(400, { error: 'Invalid sync request' });
};

function parseMobileSyncPullRequest(value: unknown): ParsedPullRequest {
  let record: JsonRecord;
  try {
    record = requireRecord(value, 'body');
    requireKnownKeys(record, PULL_BODY_KEYS, 'body');
    const deviceId = requirePostgresString(record.deviceId, 'body.deviceId');
    if (deviceId.trim().length === 0) invalidPullRequest();
  } catch (error) {
    if (error instanceof PullRequestParseFailure) throw error;
    if (error instanceof PreferenceValidationError) invalidPullRequest();
    throw error;
  }

  let profileId: string | null = null;
  if (Object.hasOwn(record, 'profileId')) {
    try {
      profileId = requirePostgresString(record.profileId, 'body.profileId');
    } catch (error) {
      if (error instanceof PreferenceValidationError) invalidPullRequest();
      throw error;
    }
    if (profileId.trim().length === 0 || !isValidLocalProfileId(profileId)) {
      invalidPullRequest();
    }
  }

  let knownEntityIds: PullRequest['knownEntityIds'];
  if (Object.hasOwn(record, 'knownEntityIds')) {
    let knownRecord: JsonRecord;
    try {
      knownRecord = requireRecord(record.knownEntityIds, 'body.knownEntityIds');
      requireKnownKeys(knownRecord, KNOWN_ENTITY_ID_KEYS, 'body.knownEntityIds');
    } catch (error) {
      if (error instanceof PreferenceValidationError) invalidPullRequest();
      throw error;
    }
    knownEntityIds = {};
    for (const key of KNOWN_ENTITY_ID_KEYS) {
      if (!Object.hasOwn(knownRecord, key)) continue;
      const list = knownRecord[key];
      if (!Array.isArray(list)) invalidPullRequest();
      const ids = list as unknown[];
      if (ids.length > MAX_PARITY_IDS) {
        throw new PullRequestParseFailure(413, {
          error: 'parity_ids_exceeds_max',
          message: `knownEntityIds.${key} contains ${ids.length} entries; maximum is ${MAX_PARITY_IDS} per request. Chunk the list client-side and issue multiple pull requests.`,
          field: key,
          maxBatch: MAX_PARITY_IDS,
          received: ids.length,
        });
      }
      if (key === 'sessionIds' || key === 'routineIds' || key === 'cycleIds') {
        for (const id of ids) {
          if (typeof id !== 'string' || !UUID_REGEX.test(id)) {
            invalidPullRequest();
          }
        }
      }
      if (key === 'sessionIds') knownEntityIds.sessionIds = ids as string[];
      else if (key === 'routineIds') knownEntityIds.routineIds = ids as string[];
      else if (key === 'cycleIds') knownEntityIds.cycleIds = ids as string[];
      else if (key === 'badgeIds') knownEntityIds.badgeIds = ids;
      else knownEntityIds.personalRecordIds = ids;
    }
  }

  let lastSync = 0;
  if (Object.hasOwn(record, 'lastSync')) {
    if (typeof record.lastSync !== 'number' || !Number.isFinite(record.lastSync)) {
      invalidPullRequest();
    }
    lastSync = record.lastSync as number;
  }
  let lastSyncISO = '';
  try {
    lastSyncISO = new Date(lastSync).toISOString();
  } catch {
    invalidPullRequest();
  }

  let requestedPageSize = DEFAULT_PAGE_SIZE;
  if (Object.hasOwn(record, 'pageSize')) {
    if (
      typeof record.pageSize !== 'number' ||
      !Number.isFinite(record.pageSize) ||
      record.pageSize < 1
    ) {
      invalidPullRequest();
    }
    requestedPageSize = record.pageSize as number;
  }
  const pageSize = Math.min(Math.floor(requestedPageSize), MAX_PAGE_SIZE);

  let cursor: DecodedCursor | null = null;
  let cursorValue: string | undefined;
  if (Object.hasOwn(record, 'cursor')) {
    if (typeof record.cursor !== 'string' || record.cursor.length === 0) {
      invalidPullRequest();
    }
    cursorValue = record.cursor as string;
    cursor = decodeCursor(cursorValue);
    if (!cursor) invalidPullRequest();
  }

  return {
    body: {
      deviceId: record.deviceId as string,
      ...(Object.hasOwn(record, 'lastSync') ? { lastSync } : {}),
      ...(profileId === null ? {} : { profileId }),
      ...(cursorValue === undefined ? {} : { cursor: cursorValue }),
      ...(Object.hasOwn(record, 'pageSize') ? { pageSize: requestedPageSize } : {}),
      ...(knownEntityIds === undefined ? {} : { knownEntityIds }),
    },
    profileId,
    lastSyncISO,
    pageSize,
    cursor,
  };
}

export interface MobileSyncPullAuthClient {
  auth: {
    getUser(jwt: string): Promise<unknown>;
  };
}

export interface MobileSyncPullHandlerDependencies {
  createAuthClient(authorization: string): MobileSyncPullAuthClient;
  createAdminClient(): SupabaseClient;
  logOperationalFailure(value: { name: string }): void;
  now(): number;
}

function defaultMobileSyncPullDependencies(): MobileSyncPullHandlerDependencies {
  return {
    createAuthClient(authorization: string) {
      return createClient(
        Deno.env.get('SUPABASE_URL')!,
        Deno.env.get('SUPABASE_ANON_KEY')!,
        {
          global: { headers: { Authorization: authorization } },
          auth: { persistSession: false, autoRefreshToken: false },
        },
      );
    },
    createAdminClient() {
      return createClient(
        Deno.env.get('SUPABASE_URL')!,
        Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
        { auth: { persistSession: false, autoRefreshToken: false } },
      );
    },
    logOperationalFailure(value: { name: string }) {
      console.error(value);
    },
    now() {
      return Date.now();
    },
  };
}

async function mobileSyncPullHandler(
  req: Request,
  dependencies: MobileSyncPullHandlerDependencies,
): Promise<Response> {
  const cors = getCorsHeaders(req);

  // CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: cors });
  }

  // POST only
  if (req.method !== 'POST') {
    return new Response(
      JSON.stringify({ error: 'Method not allowed' }),
      { status: 405, headers: { ...cors, 'Content-Type': 'application/json' } }
    );
  }

  try {
    // =========================================================================
    // 1. JWT verification — authenticate the mobile user
    // =========================================================================
    const authorization = req.headers.get('Authorization');
    const bearerMatch = authorization === null
      ? null
      : /^Bearer ([^\s]+)$/.exec(authorization);
    if (!bearerMatch) {
      return new Response(
        JSON.stringify({ error: 'Missing bearer token' }),
        { status: 401, headers: { ...cors, 'Content-Type': 'application/json' } }
      );
    }
    const userJwt = bearerMatch[1];

    const authOperationalFailure = (error: unknown): Response => {
      dependencies.logOperationalFailure({
        name: safeErrorName(error, 'AuthOperationalFailure'),
      });
      return new Response(
        JSON.stringify({ error: 'Authentication service unavailable' }),
        { status: 503, headers: { ...cors, 'Content-Type': 'application/json' } },
      );
    };

    const authClient = dependencies.createAuthClient(authorization!);
    let authResult: unknown;
    try {
      authResult = await authClient.auth.getUser(userJwt);
    } catch (error) {
      return authOperationalFailure(error);
    }
    if (typeof authResult !== 'object' || authResult === null || Array.isArray(authResult)) {
      return authOperationalFailure({ name: 'AuthUnexpectedResult' });
    }
    const authRecord = authResult as JsonRecord;
    if (!Object.hasOwn(authRecord, 'error') || !Object.hasOwn(authRecord, 'data')) {
      return authOperationalFailure({ name: 'AuthUnexpectedResult' });
    }
    const userError = authRecord.error;
    if (userError !== null) {
      const status = returnedAuthStatus(userError);
      if (status === 400 || status === 401 || status === 403) {
        return new Response(
          JSON.stringify({ error: 'Invalid bearer token' }),
          { status: 401, headers: { ...cors, 'Content-Type': 'application/json' } },
        );
      }
      return authOperationalFailure(userError);
    }
    const userData = authRecord.data;
    if (typeof userData !== 'object' || userData === null || Array.isArray(userData)) {
      return authOperationalFailure({ name: 'AuthUnexpectedResult' });
    }
    const verifiedUser = (userData as JsonRecord).user;
    if (
      typeof verifiedUser !== 'object' || verifiedUser === null || Array.isArray(verifiedUser) ||
      typeof (verifiedUser as JsonRecord).id !== 'string' ||
      ((verifiedUser as JsonRecord).id as string).trim().length === 0
    ) {
      return authOperationalFailure({ name: 'AuthUnexpectedResult' });
    }
    const verifiedUserId = (verifiedUser as JsonRecord).id as string;
    const userId = verifiedUserId;

    // =========================================================================
    // 2. Strict request parsing before privileged construction
    // =========================================================================
    let parsedRequest: ParsedPullRequest;
    try {
      parsedRequest = parseMobileSyncPullRequest(await req.json());
    } catch (error) {
      if (error instanceof PullRequestParseFailure) {
        return new Response(JSON.stringify(error.body), {
          status: error.status,
          headers: { ...cors, 'Content-Type': 'application/json' },
        });
      }
      if (error instanceof SyntaxError || error instanceof PreferenceValidationError) {
        return new Response(
          JSON.stringify({ error: 'Invalid sync request' }),
          { status: 400, headers: { ...cors, 'Content-Type': 'application/json' } },
        );
      }
      throw error;
    }
    const { body, profileId, lastSyncISO, pageSize, cursor } = parsedRequest;

    // =========================================================================
    // 3. Service-role client for DB queries (bypasses RLS)
    // =========================================================================
    // SECURITY: Using service role key bypasses Row Level Security.
    // ALL queries MUST include .eq('user_id', userId) for user isolation.
    // Review any new query additions for this requirement.
    const supabase = dependencies.createAdminClient();

    const rateCheck = await checkRateLimit(supabase, {
      key: 'mobile-sync-pull',
      userId,
      maxRequests: 20,
      windowSeconds: 60,
    }, cors);
    if (!rateCheck.allowed) return rateCheck.response!;

    const emberGate = await requireSubscription(supabase, userId, 'EMBER', cors);
    if (!emberGate.allowed) return emberGate.response!;

    let profilePreferenceSections: ReturnType<typeof parsePullPreferenceRow> | undefined;
    if (cursor === null && profileId !== null) {
      try {
        const { data: preferenceRow, error: preferenceError } = await supabase
          .from('local_profile_preferences')
          .select(
            'local_profile_id,body_weight_kg,weight_unit,weight_increment,' +
            'core_revision,core_updated_at,equipment_rack,rack_revision,rack_updated_at,' +
            'workout_preferences,workout_revision,workout_updated_at,' +
            'led_color_scheme_id,led_preferences,led_revision,led_updated_at,' +
            'vbt_enabled,vbt_preferences,vbt_revision,vbt_updated_at',
          )
          .eq('user_id', verifiedUserId)
          .eq('local_profile_id', profileId)
          .maybeSingle();
        if (preferenceError) {
          throw new PreferenceInfrastructureError('preference pull');
        }
        if (preferenceRow) {
          profilePreferenceSections = parsePullPreferenceRow(preferenceRow, profileId);
        }
      } catch (error) {
        dependencies.logOperationalFailure({
          name: safeErrorName(error, 'PreferenceInfrastructureFailure'),
        });
        return new Response(
          JSON.stringify({ error: 'Sync temporarily unavailable' }),
          { status: 503, headers: { ...cors, 'Content-Type': 'application/json' } },
        );
      }
    }

    const syncTime = dependencies.now();

    // DIAGNOSTIC: Log incoming request parameters
    console.log('[PULL] Request:', {
      userId,
      parityMode: isParityMode(body),
      knownSessions: body.knownEntityIds?.sessionIds?.length ?? 0,
      knownRoutines: body.knownEntityIds?.routineIds?.length ?? 0,
      knownCycles: body.knownEntityIds?.cycleIds?.length ?? 0,
      knownBadges: body.knownEntityIds?.badgeIds?.length ?? 0,
      knownPersonalRecords: body.knownEntityIds?.personalRecordIds?.length ?? 0,
      lastSync: body.lastSync, // Legacy
      profileId,
      cursor: body.cursor,
    });

    // Pagination has already been validated before privileged construction.
    const startType: EntityType = cursor?.type ?? 'sessions';
    const startTypeIndex = ENTITY_ORDER.indexOf(startType);

    // Track pagination state for response
    let nextCursor: string | null = null;
    let hasMore = false;
    let remainingPageSize = pageSize;

    // Initialize result containers (will be populated as we page through entity types)
    let sessionDtos: Record<string, unknown>[] = [];
    let routineDtos: Record<string, unknown>[] = [];
    let cycleDtos: Record<string, unknown>[] = [];
    let badgeDtos: Record<string, unknown>[] = [];
    let gamificationDto: Record<string, unknown> | null = null;
    let rpgDto: Record<string, unknown> | null = null;
    let personalRecordDtos: Record<string, unknown>[] = [];
    let localProfiles: Record<string, unknown>[] = [];
    let externalActivityDtos: Record<string, unknown>[] = [];
    let customExerciseDtos: Record<string, unknown>[] = [];

    // =========================================================================
    // 4. Paginated fetch of entities in order: sessions → routines → cycles → badges → stats → customExercises
    //    We fetch pageSize+1 to detect hasMore, then trim to pageSize.
    // =========================================================================

    // Helper to build cursor condition for stable ordering (updated_at ASC, id ASC)
    function buildCursorCondition(cursorData: DecodedCursor | null, entityType: EntityType): {
      cursorUpdatedAt: string | null;
      cursorId: string | null;
    } {
      if (!cursorData || cursorData.type !== entityType) {
        return { cursorUpdatedAt: null, cursorId: null };
      }
      return {
        cursorUpdatedAt: new Date(cursorData.updatedAt).toISOString(),
        cursorId: cursorData.id,
      };
    }

    // ─── SESSIONS ───────────────────────────────────────────────────────────
    // Using RPC function to bypass URL length limits for large parity ID lists.
    // RPC uses POST body, so no limit on number of IDs (unlike .not().in() which uses GET).
    if (startTypeIndex <= ENTITY_ORDER.indexOf('sessions') && remainingPageSize > 0) {
      const { cursorUpdatedAt, cursorId } = buildCursorCondition(cursor, 'sessions');
      const knownSessionIds = body.knownEntityIds?.sessionIds ?? [];

      // Use RPC for parity mode OR full sync. Legacy timestamp mode still uses direct query.
      const useRpc = knownSessionIds.length > 0 || !body.lastSync || body.lastSync === 0;

      let sessionsRaw: Record<string, unknown>[] = [];
      let sessionsError: { code?: string; message?: string; hint?: string } | null = null;

      if (useRpc) {
        // RPC function handles: NOT IN filter, profile filter, cursor, ordering, limit
        const { data, error } = await supabase.rpc('get_sessions_excluding_ids', {
          p_user_id: userId,
          p_known_ids: knownSessionIds,
          p_profile_id: profileId,
          p_cursor_updated_at: cursorUpdatedAt,
          p_cursor_id: cursorId,
          p_limit: remainingPageSize + 1, // +1 to detect hasMore
        });
        sessionsRaw = (data as Record<string, unknown>[]) ?? [];
        sessionsError = error;
      } else {
        // Legacy timestamp-based mode (backward compatibility)
        let sessionsQuery = supabase
          .from('workout_sessions')
          .select('*')
          .eq('user_id', userId)
          .or(`updated_at.gt.${lastSyncISO},started_at.gt.${lastSyncISO}`)
          .order('updated_at', { ascending: true })
          .order('id', { ascending: true })
          .limit(remainingPageSize + 1);

        if (profileId) {
          if (profileId === 'default') {
            sessionsQuery = sessionsQuery.is('local_profile_id', null);
          } else {
            sessionsQuery = sessionsQuery.or(`local_profile_id.eq.${profileId},local_profile_id.is.null`);
          }
        }

        if (cursorUpdatedAt && cursorId) {
          sessionsQuery = sessionsQuery.or(
            `updated_at.gt.${cursorUpdatedAt},and(updated_at.eq.${cursorUpdatedAt},id.gt.${cursorId})`
          );
        }

        const { data, error } = await sessionsQuery;
        sessionsRaw = (data as Record<string, unknown>[]) ?? [];
        sessionsError = error;
      }

      if (sessionsError) {
        console.error('Error fetching sessions:', sessionsError);
        return new Response(
          JSON.stringify({
            error: 'Failed to fetch workout sessions',
            code: sessionsError.code ?? 'UNKNOWN',
            details: sessionsError.message ?? sessionsError.hint ?? null,
            parityIdCount: knownSessionIds.length,
          }),
          { status: 500, headers: { ...cors, 'Content-Type': 'application/json' } }
        );
      }

      // Check if there are more sessions
      if (sessionsRaw.length > remainingPageSize) {
        hasMore = true;
        const lastSession = sessionsRaw[remainingPageSize - 1];
        const updatedAtRaw = lastSession.updated_at ?? lastSession.started_at;
        const updatedAtMs = updatedAtRaw
          ? new Date(updatedAtRaw as string).getTime()
          : dependencies.now();
        nextCursor = encodeCursor('sessions', updatedAtMs, lastSession.id as string);
        sessionsRaw.splice(remainingPageSize); // Trim to pageSize
      }

      // Fetch child records for sessions in this page
      const sessionIds = sessionsRaw.map((s: Record<string, unknown>) => s.id as string);
      let exercisesRaw: Record<string, unknown>[] = [];
      let setsRaw: Record<string, unknown>[] = [];
      let repSummariesRaw: Record<string, unknown>[] = [];

      if (sessionIds.length > 0) {
        const { data: exercises, error: exercisesError } = await supabase
          .from('exercises')
          .select('*')
          .in('session_id', sessionIds)
          .order('order_index', { ascending: true });
        if (exercisesError) {
          return readFailure('session exercises', exercisesError, cors);
        }
        exercisesRaw = exercises ?? [];

        const exerciseIds = exercisesRaw.map((e) => e.id as string);

        if (exerciseIds.length > 0) {
          const { data: sets, error: setsError } = await supabase
            .from('sets')
            .select('*')
            .in('exercise_id', exerciseIds);
          if (setsError) {
            return readFailure('session sets', setsError, cors);
          }
          setsRaw = sets ?? [];

          const setIds = setsRaw.map((s) => s.id as string);

          if (setIds.length > 0) {
            const { data: repSums, error: repSummariesError } = await supabase
              .from('rep_summaries')
              .select('*')
              .in('set_id', setIds);
            if (repSummariesError) {
              return readFailure('session rep summaries', repSummariesError, cors);
            }
            repSummariesRaw = repSums ?? [];
          }
        }
      }

      // Assemble nested session hierarchy
      const repSummariesBySetId = new Map<string, Record<string, unknown>[]>();
      for (const rs of repSummariesRaw) {
        const setId = rs.set_id as string;
        if (!repSummariesBySetId.has(setId)) {
          repSummariesBySetId.set(setId, []);
        }
        repSummariesBySetId.get(setId)!.push(rs);
      }

      const setsByExerciseId = new Map<string, Record<string, unknown>[]>();
      for (const s of setsRaw) {
        const exerciseId = s.exercise_id as string;
        if (!setsByExerciseId.has(exerciseId)) {
          setsByExerciseId.set(exerciseId, []);
        }
        const setRepSummaries = repSummariesBySetId.get(s.id as string) ?? [];
        setsByExerciseId.get(exerciseId)!.push({
          ...s,
          _repSummaries: setRepSummaries,
        });
      }

      const exercisesBySessionId = new Map<string, Record<string, unknown>[]>();
      for (const e of exercisesRaw) {
        const sessionId = e.session_id as string;
        if (!exercisesBySessionId.has(sessionId)) {
          exercisesBySessionId.set(sessionId, []);
        }
        const exerciseSets = setsByExerciseId.get(e.id as string) ?? [];
        exercisesBySessionId.get(sessionId)!.push({
          ...e,
          _sets: exerciseSets,
        });
      }

      sessionDtos = sessionsRaw.map((ws: Record<string, unknown>) => {
        const wsExercises = exercisesBySessionId.get(ws.id as string) ?? [];
        return {
          id: ws.id,
          userId: ws.user_id,
          name: ws.name,
          startedAt: ws.started_at,
          durationSeconds: ws.duration_seconds,
          totalVolume: ws.total_volume,
          setCount: ws.set_count,
          exerciseCount: ws.exercise_count,
          prCount: ws.pr_count,
          routineName: ws.routine_name,
          workoutMode: ws.workout_mode,
          routineSessionId: ws.routine_session_id,
          notes: ws.notes ?? null,
          // Phase 3.3 (audit item #1): server-canonical updatedAt for the
          // mobile-side LWW pull merge gate. Mobile parses this via
          // kotlin.time.Instant in PortalPullAdapter and feeds it to
          // SyncRepository.mergeSessionsLww as the per-session timestamp.
          updatedAt: ws.updated_at ?? null,
          avgVelocityMps: ws.avg_velocity_mps,
          avgAsymmetryPct: ws.avg_asymmetry_pct,
          velocityLossPct: ws.velocity_loss_pct,
          dominantSide: ws.dominant_side,
          strengthProfile: ws.strength_profile,
          formScore: ws.form_score,
          deloadWarnings: ws.deload_warnings,
          romViolations: ws.rom_violations,
          spotterActivations: ws.spotter_activations,
          peakForceN: ws.peak_force_n,
          estimatedCalories: ws.estimated_calories,
          heaviestLiftKg: ws.heaviest_lift_kg,
          eccentricLoad: ws.eccentric_load,
          echoLevel: ws.echo_level,
          warmupReps: ws.warmup_reps,
          workingReps: ws.working_reps,
          exercises: wsExercises.map((ex) => ({
            id: ex.id,
            sessionId: ex.session_id,
            exerciseId: ex.exercise_id ?? null,
            name: ex.name,
            muscleGroup: ex.muscle_group,
            orderIndex: ex.order_index,
            sets: ((ex._sets as Record<string, unknown>[]) ?? []).map((st) => ({
              id: st.id,
              exerciseId: st.exercise_id,
              setNumber: st.set_number,
              targetReps: st.target_reps,
              actualReps: st.actual_reps,
              weightKg: st.weight_kg,
              rpe: st.rpe,
              isPr: st.is_pr,
              notes: st.notes,
              workoutMode: st.workout_mode,
              repSummaries: ((st._repSummaries as Record<string, unknown>[]) ?? []).map((rs) => ({
                id: rs.id,
                setId: rs.set_id,
                repNumber: rs.rep_number,
                meanVelocityMps: rs.mean_velocity_mps,
                peakVelocityMps: rs.peak_velocity_mps,
                meanForceN: rs.mean_force_n,
                peakForceN: rs.peak_force_n,
                powerWatts: rs.power_watts,
                romMm: rs.rom_mm,
                tutMs: rs.tut_ms,
                leftForceAvg: rs.left_force_avg,
                rightForceAvg: rs.right_force_avg,
                asymmetryPct: rs.asymmetry_pct,
                vbtZone: rs.vbt_zone,
              })),
            })),
          })),
        };
      });

      remainingPageSize -= sessionDtos.length;
    }

    // ─── ROUTINES ───────────────────────────────────────────────────────────
    // Using RPC function to bypass URL length limits for large parity ID lists.
    if (!hasMore && startTypeIndex <= ENTITY_ORDER.indexOf('routines') && remainingPageSize > 0) {
      const { cursorUpdatedAt, cursorId } = buildCursorCondition(cursor, 'routines');
      const knownRoutineIds = body.knownEntityIds?.routineIds ?? [];

      const useRpc = knownRoutineIds.length > 0 || !body.lastSync || body.lastSync === 0;

      let routinesData: Record<string, unknown>[] = [];

      if (useRpc) {
        const { data, error } = await supabase.rpc('get_routines_excluding_ids', {
          p_user_id: userId,
          p_known_ids: knownRoutineIds,
          p_profile_id: profileId,
          p_cursor_updated_at: cursorUpdatedAt,
          p_cursor_id: cursorId,
          p_limit: remainingPageSize + 1,
          p_last_sync_at: lastSyncISO,
        });
        if (error) return readFailure('routines', error, cors);
        routinesData = (data as Record<string, unknown>[]) ?? [];
      } else {
        // Legacy timestamp-based mode
        let routinesQuery = supabase
          .from('routines')
          .select('*')
          .eq('user_id', userId)
          .gt('updated_at', lastSyncISO)
          .order('updated_at', { ascending: true })
          .order('id', { ascending: true })
          .limit(remainingPageSize + 1);

        if (profileId) {
          if (profileId === 'default') {
            routinesQuery = routinesQuery.is('local_profile_id', null);
          } else {
            routinesQuery = routinesQuery.or(`local_profile_id.eq.${profileId},local_profile_id.is.null`);
          }
        }

        if (cursorUpdatedAt && cursorId) {
          routinesQuery = routinesQuery.or(
            `updated_at.gt.${cursorUpdatedAt},and(updated_at.eq.${cursorUpdatedAt},id.gt.${cursorId})`
          );
        }

        const { data, error } = await routinesQuery;
        if (error) return readFailure('routines', error, cors);
        routinesData = (data as Record<string, unknown>[]) ?? [];
      }

      if (routinesData.length > remainingPageSize) {
        hasMore = true;
        const lastRoutine = routinesData[remainingPageSize - 1];
        const updatedAtMs = new Date(lastRoutine.updated_at as string).getTime();
        nextCursor = encodeCursor('routines', updatedAtMs, lastRoutine.id as string);
        routinesData.splice(remainingPageSize);
      }

      // Fetch routine exercises
      const routineIds = routinesData.map((r: Record<string, unknown>) => r.id as string);
      let routineExercisesRaw: Record<string, unknown>[] = [];
      if (routineIds.length > 0) {
        const { data: re, error: reError } = await supabase
          .from('routine_exercises')
          .select(`
            *,
            catalog:exercise_catalog(display_name, equipment)
          `)
          .in('routine_id', routineIds);
        if (reError) return readFailure('routine exercises', reError, cors);
        routineExercisesRaw = re ?? [];
      }

      const reByRoutineId = new Map<string, Record<string, unknown>[]>();
      for (const re of routineExercisesRaw) {
        const routineId = re.routine_id as string;
        if (!reByRoutineId.has(routineId)) {
          reByRoutineId.set(routineId, []);
        }
        reByRoutineId.get(routineId)!.push(re);
      }

      routineDtos = routinesData.map((r: Record<string, unknown>) => {
        const rExercises = reByRoutineId.get(r.id as string) ?? [];
        return {
          id: r.id,
          userId: r.user_id,
          name: r.name,
          description: r.description,
          exerciseCount: r.exercise_count,
          estimatedDuration: r.estimated_duration,
          timesCompleted: r.times_completed,
          isFavorite: r.is_favorite,
          updatedAt: r.updated_at ? new Date(r.updated_at as string).getTime() : null,
          exercises: rExercises.map((re) => ({
            id: re.id,
            routineId: re.routine_id,
            exerciseId: re.exercise_id ?? null,
            displayName: (re.catalog as Record<string, unknown> | null)?.display_name ?? re.name,
            exerciseEquipment: (re.catalog as Record<string, unknown> | null)?.equipment
              ? ((re.catalog as Record<string, unknown>).equipment as string[]).join(",")
              : null,
            name: re.name,
            muscleGroup: re.muscle_group,
            sets: re.sets,
            reps: re.reps,
            weight: re.weight,
            restSeconds: re.rest_seconds,
            mode: re.mode,
            orderIndex: re.order_index,
            supersetId: re.superset_id,
            supersetColor: re.superset_color,
            supersetOrder: re.superset_order,
            perSetWeights: re.per_set_weights != null ? JSON.stringify(re.per_set_weights) : null,
            perSetRest: re.per_set_rest != null ? JSON.stringify(re.per_set_rest) : null,
            perSetReps: re.per_set_reps != null ? JSON.stringify(re.per_set_reps) : null,
            isAmrap: re.is_amrap,
            isBodyweight: re.is_bodyweight ?? false,
            prPercentage: re.pr_percentage,
            repCountTiming: re.rep_count_timing,
            stopAtPosition: re.stop_at_position,
            stallDetection: re.stall_detection,
            eccentricLoad: re.eccentric_load,
            echoLevel: re.echo_level,
            perSetEchoLevels: re.per_set_echo_levels ?? null,
            warmupSets: re.warmup_sets ?? null,
          })),
        };
      });

      remainingPageSize -= routineDtos.length;
    }

    // ─── CYCLES ─────────────────────────────────────────────────────────────
    // Using RPC function to bypass URL length limits for large parity ID lists.
    if (!hasMore && startTypeIndex <= ENTITY_ORDER.indexOf('cycles') && remainingPageSize > 0) {
      const { cursorUpdatedAt, cursorId } = buildCursorCondition(cursor, 'cycles');
      const knownCycleIds = body.knownEntityIds?.cycleIds ?? [];

      const useRpc = knownCycleIds.length > 0 || !body.lastSync || body.lastSync === 0;

      let cyclesData: Record<string, unknown>[] = [];

      if (useRpc) {
        const { data, error } = await supabase.rpc('get_cycles_excluding_ids', {
          p_user_id: userId,
          p_known_ids: knownCycleIds,
          p_profile_id: profileId,
          p_cursor_updated_at: cursorUpdatedAt,
          p_cursor_id: cursorId,
          p_limit: remainingPageSize + 1,
          p_last_sync_at: lastSyncISO,
        });
        if (error) return readFailure('cycles', error, cors);
        cyclesData = (data as Record<string, unknown>[]) ?? [];
      } else {
        // Legacy timestamp-based mode
        let cyclesQuery = supabase
          .from('training_cycles')
          .select('*')
          .eq('user_id', userId)
          .gt('updated_at', lastSyncISO)
          .order('updated_at', { ascending: true })
          .order('id', { ascending: true })
          .limit(remainingPageSize + 1);

        if (profileId) {
          if (profileId === 'default') {
            cyclesQuery = cyclesQuery.is('local_profile_id', null);
          } else {
            cyclesQuery = cyclesQuery.or(`local_profile_id.eq.${profileId},local_profile_id.is.null`);
          }
        }

        if (cursorUpdatedAt && cursorId) {
          cyclesQuery = cyclesQuery.or(
            `updated_at.gt.${cursorUpdatedAt},and(updated_at.eq.${cursorUpdatedAt},id.gt.${cursorId})`
          );
        }

        const { data, error } = await cyclesQuery;
        if (error) return readFailure('cycles', error, cors);
        cyclesData = (data as Record<string, unknown>[]) ?? [];
      }

      if (cyclesData.length > remainingPageSize) {
        hasMore = true;
        const lastCycle = cyclesData[remainingPageSize - 1];
        const updatedAtMs = new Date(lastCycle.updated_at as string).getTime();
        nextCursor = encodeCursor('cycles', updatedAtMs, lastCycle.id as string);
        cyclesData.splice(remainingPageSize);
      }

      // Fetch cycle days
      const cycleIds = cyclesData.map((c: Record<string, unknown>) => c.id as string);
      let cycleDaysRaw: Record<string, unknown>[] = [];
      if (cycleIds.length > 0) {
        const { data: cd, error: cdError } = await supabase
          .from('cycle_days')
          .select('*')
          .in('cycle_id', cycleIds);
        if (cdError) return readFailure('cycle days', cdError, cors);
        cycleDaysRaw = cd ?? [];
      }

      const daysByCycleId = new Map<string, Record<string, unknown>[]>();
      for (const d of cycleDaysRaw) {
        const cycleId = d.cycle_id as string;
        if (!daysByCycleId.has(cycleId)) {
          daysByCycleId.set(cycleId, []);
        }
        daysByCycleId.get(cycleId)!.push(d);
      }

      cycleDtos = cyclesData.map((c: Record<string, unknown>) => {
        const cDays = daysByCycleId.get(c.id as string) ?? [];
        return {
          id: c.id,
          userId: c.user_id,
          name: c.name,
          description: c.description,
          durationWeeks: c.duration_weeks,
          workoutDays: c.workout_days,
          restDays: c.rest_days,
          currentWeek: c.current_week,
          status: c.status,
          startedAt: c.started_at,
          lastUsedAt: c.last_used_at,
          progressionSettings: c.progression_settings != null ? JSON.stringify(c.progression_settings) : null,
          deloadSettings: c.deload_settings != null ? JSON.stringify(c.deload_settings) : null,
          templateId: c.template_id ?? null,
          days: cDays.map((d) => ({
            id: d.id,
            cycleId: d.cycle_id,
            dayNumber: d.day_number,
            dayType: d.day_type,
            routineId: d.routine_id,
            weightAdjustment: d.weight_adjustment,
            repModifier: d.rep_modifier,
            restOverride: d.rest_override,
            restType: d.rest_type,
            notes: d.notes,
          })),
        };
      });

      remainingPageSize -= cycleDtos.length;
    }

    // ─── BADGES ─────────────────────────────────────────────────────────────
    // Using RPC function to bypass URL length limits for large parity ID lists.
    if (!hasMore && startTypeIndex <= ENTITY_ORDER.indexOf('badges') && remainingPageSize > 0) {
      const { cursorUpdatedAt, cursorId } = buildCursorCondition(cursor, 'badges');
      const knownBadgeIds = uuidParityIds(body.knownEntityIds?.badgeIds);

      const useRpc = knownBadgeIds.length > 0 || !body.lastSync || body.lastSync === 0;

      let badgesData: Record<string, unknown>[] = [];

      if (useRpc) {
        const { data, error } = await supabase.rpc('get_badges_excluding_ids', {
          p_user_id: userId,
          p_known_ids: knownBadgeIds,
          p_cursor_earned_at: cursorUpdatedAt,
          p_cursor_id: cursorId,
          p_limit: remainingPageSize + 1,
        });
        if (error) return readFailure('badges', error, cors);
        badgesData = (data as Record<string, unknown>[]) ?? [];
      } else {
        // Legacy timestamp-based mode
        let badgesQuery = supabase
          .from('earned_badges')
          .select('*')
          .eq('user_id', userId)
          .gt('earned_at', lastSyncISO)
          .order('earned_at', { ascending: true })
          .order('id', { ascending: true })
          .limit(remainingPageSize + 1);

        if (cursorUpdatedAt && cursorId) {
          badgesQuery = badgesQuery.or(
            `earned_at.gt.${cursorUpdatedAt},and(earned_at.eq.${cursorUpdatedAt},id.gt.${cursorId})`
          );
        }

        const { data, error } = await badgesQuery;
        if (error) return readFailure('badges', error, cors);
        badgesData = (data as Record<string, unknown>[]) ?? [];
      }

      if (badgesData.length > remainingPageSize) {
        hasMore = true;
        const lastBadge = badgesData[remainingPageSize - 1];
        const earnedAtMs = new Date(lastBadge.earned_at as string).getTime();
        nextCursor = encodeCursor('badges', earnedAtMs, String(lastBadge.id));
        badgesData.splice(remainingPageSize);
      }

      badgeDtos = badgesData.map((b: Record<string, unknown>) => ({
        id: b.id,
        userId: b.user_id,
        badgeId: b.badge_id,
        badgeName: b.badge_name,
        badgeDescription: b.badge_description,
        badgeTier: b.badge_tier,
        earnedAt: b.earned_at,
      }));

      remainingPageSize -= badgeDtos.length;
    }

    // ─── STATS (RPG + Gamification) ─────────────────────────────────────────
    // Stats are singleton records per user, so we fetch them on the final page
    if (!hasMore && startTypeIndex <= ENTITY_ORDER.indexOf('stats')) {
      // RPG attributes (delta sync)
      const { data: rpgAttributes, error: rpgError } = await supabase
        .from('rpg_attributes')
        .select('*')
        .eq('user_id', userId)
        .gt('updated_at', lastSyncISO)
        .maybeSingle();
      if (rpgError) return readFailure('rpg attributes', rpgError, cors);

      rpgDto = rpgAttributes
        ? {
            id: rpgAttributes.id,
            userId: rpgAttributes.user_id,
            // fix(audit #8): defensively round integer fields before wire send
            // so kotlinx.serialization on mobile cannot see a float in an Int
            // slot. See _shared/rpgSchema.ts for the contract.
            strength: Math.round(Number(rpgAttributes.strength ?? 0)),
            power: Math.round(Number(rpgAttributes.power ?? 0)),
            stamina: Math.round(Number(rpgAttributes.stamina ?? 0)),
            consistency: Math.round(Number(rpgAttributes.consistency ?? 0)),
            mastery: Math.round(Number(rpgAttributes.mastery ?? 0)),
            characterClass: rpgAttributes.character_class,
            level: Math.round(Number(rpgAttributes.level ?? 1)),
            experiencePoints: Math.round(Number(rpgAttributes.experience_points ?? 0)),
            updatedAt: rpgAttributes.updated_at,
          }
        : null;

      // Gamification stats (delta sync)
      const { data: gamificationStats, error: gamificationError } = await supabase
        .from('gamification_stats')
        .select('*')
        .eq('user_id', userId)
        .gt('updated_at', lastSyncISO)
        .maybeSingle();
      if (gamificationError) return readFailure('gamification stats', gamificationError, cors);

      gamificationDto = gamificationStats
        ? {
            id: gamificationStats.id,
            userId: gamificationStats.user_id,
            totalWorkouts: gamificationStats.total_workouts,
            totalReps: gamificationStats.total_reps,
            totalVolumeKg: gamificationStats.total_volume_kg,
            longestStreak: gamificationStats.longest_streak,
            currentStreak: gamificationStats.current_streak,
            totalTimeSeconds: gamificationStats.total_time_seconds,
            updatedAt: gamificationStats.updated_at,
          }
        : null;

      // Local profiles (always included on final page)
      const { data: profilesData, error: profilesError } = await supabase
        .from('local_profiles')
        .select('id, name, color_index, device_id, created_at, updated_at')
        .eq('user_id', userId);
      if (profilesError) return readFailure('local profiles', profilesError, cors);
      // Transform to camelCase for mobile DTO compatibility
      localProfiles = (profilesData ?? []).map((p: Record<string, unknown>) => ({
        id: p.id,
        name: p.name,
        colorIndex: p.color_index,
      }));

      // External activities (EMBER+ enforced at handler start)
      // fix(M-25): cap at 500 rows to bound memory — external activities carry
      // large rawData JSON payloads; without a limit a user importing years of
      // Strava history could exhaust Edge Function memory in a single response.
      const { data: externalActivitiesRaw, error: externalActivitiesError } = await supabase
        .from('external_activities')
        .select('*')
        .eq('user_id', userId)
        .gt('synced_at', lastSyncISO)
        .order('synced_at', { ascending: true })
        .limit(500);
      if (externalActivitiesError) return readFailure('external activities', externalActivitiesError, cors);

      externalActivityDtos = (externalActivitiesRaw ?? []).map((a: Record<string, unknown>) => ({
        id: a.id,
        externalId: a.external_id,
        provider: a.provider,
        name: a.name,
        activityType: a.activity_type,
        startedAt: a.started_at,
        durationSeconds: a.duration_seconds,
        distanceMeters: a.distance_meters,
        calories: a.calories,
        avgHeartRate: a.avg_heart_rate,
        maxHeartRate: a.max_heart_rate,
        elevationGainMeters: a.elevation_gain_meters,
        rawData: a.raw_data != null ? JSON.stringify(a.raw_data) : null,
      }));
    }

    // ─── PERSONAL RECORDS ───────────────────────────────────────────────────
    // fix(M-24): was fetched without any row limit inside the stats block,
    // exposing unbounded memory on power users with large PR histories.
    // Moved here with full pagination guards matching other entity types:
    // remainingPageSize + 1 fetch, trim to pageSize, cursor encode on overflow.
    // Using RPC function to bypass URL length limits for large parity ID lists.
    if (!hasMore && startTypeIndex <= ENTITY_ORDER.indexOf('personalRecords') && remainingPageSize > 0) {
      const { cursorUpdatedAt, cursorId } = buildCursorCondition(cursor, 'personalRecords');
      const knownPRIds = uuidParityIds(body.knownEntityIds?.personalRecordIds);

      const useRpcPR = knownPRIds.length > 0 || !body.lastSync || body.lastSync === 0;

      let personalRecordsData: Record<string, unknown>[] = [];

      if (useRpcPR) {
        // RPC path: excludes IDs the client already has; chain order + limit
        // client-side because get_personal_records_excluding_ids has no p_limit
        // or cursor params (unlike get_cycles_excluding_ids / get_badges_excluding_ids).
        let prQuery = supabase.rpc('get_personal_records_excluding_ids', {
          p_user_id: userId,
          p_known_ids: knownPRIds,
          p_profile_id: profileId,
          p_since: lastSyncISO,
        })
          .order('updated_at', { ascending: true })
          .order('id', { ascending: true })
          .limit(remainingPageSize + 1);

        if (cursorUpdatedAt && cursorId) {
          prQuery = prQuery.or(
            `updated_at.gt.${cursorUpdatedAt},and(updated_at.eq.${cursorUpdatedAt},id.gt.${cursorId})`
          );
        }

        const { data, error } = await prQuery;
        if (error) return readFailure('personal records', error, cors);
        personalRecordsData = (data as Record<string, unknown>[]) ?? [];
      } else {
        // Legacy timestamp-based mode
        let personalRecordsQuery = supabase
          .from('personal_records')
          .select('*')
          .eq('user_id', userId)
          .gt('updated_at', lastSyncISO)
          .order('updated_at', { ascending: true })
          .order('id', { ascending: true })
          .limit(remainingPageSize + 1);

        if (profileId) {
          personalRecordsQuery = personalRecordsQuery.or(
            buildLocalProfileOrNullPostgrestFilter(profileId),
          );
        }

        if (cursorUpdatedAt && cursorId) {
          personalRecordsQuery = personalRecordsQuery.or(
            `updated_at.gt.${cursorUpdatedAt},and(updated_at.eq.${cursorUpdatedAt},id.gt.${cursorId})`
          );
        }

        const { data, error } = await personalRecordsQuery;
        if (error) return readFailure('personal records', error, cors);
        personalRecordsData = (data as Record<string, unknown>[]) ?? [];
      }

      if (personalRecordsData.length > remainingPageSize) {
        hasMore = true;
        const lastPR = personalRecordsData[remainingPageSize - 1];
        const updatedAtMs = new Date(lastPR.updated_at as string).getTime();
        nextCursor = encodeCursor('personalRecords', updatedAtMs, lastPR.id as string);
        personalRecordsData.splice(remainingPageSize);
      }

      personalRecordDtos = personalRecordsData.map((pr: Record<string, unknown>) => ({
        id: pr.id,
        userId: pr.user_id,
        // fix(F351): preserve catalog exercise linkage and profile scope so the
        // mobile side does not lose exerciseId/localProfileId on pull. Push
        // accepts these fields and the RPC/query returns the snake_case columns.
        exerciseId: pr.exercise_id ?? null,
        localProfileId: pr.local_profile_id ?? null,
        exerciseName: pr.exercise_name,
        muscleGroup: pr.muscle_group,
        recordType: pr.record_type,
        value: pr.value,
        weightKg: pr.weight_kg,
        reps: pr.reps,
        workoutPhase: pr.workout_phase,
        sessionId: pr.session_id,
        achievedAt: pr.achieved_at,
        updatedAt: pr.updated_at,
        deletedAt: pr.deleted_at ?? null,
      }));

      remainingPageSize -= personalRecordDtos.length;
    }

    // =========================================================================
    // 6. Return user's custom exercises from catalog
    // =========================================================================
    if (!hasMore && startTypeIndex <= ENTITY_ORDER.indexOf('customExercises') && remainingPageSize > 0) {
      const { cursorUpdatedAt, cursorId } = buildCursorCondition(cursor, 'customExercises');

      let customExercisesQuery = supabase
        .from("exercise_catalog")
        .select("*")
        .eq("is_custom", true)
        .eq("user_id", userId)
        .gt("updated_at", lastSyncISO)
        .order("updated_at", { ascending: true })
        .order("id", { ascending: true })
        .limit(remainingPageSize + 1);

      if (cursorUpdatedAt && cursorId) {
        customExercisesQuery = customExercisesQuery.or(
          `updated_at.gt.${cursorUpdatedAt},and(updated_at.eq.${cursorUpdatedAt},id.gt.${cursorId})`
        );
      }

      const { data: customExercises, error: customExercisesError } = await customExercisesQuery;

      if (customExercisesError) {
        console.error('Error fetching custom exercises:', customExercisesError);
        return new Response(
          JSON.stringify({
            error: 'Failed to fetch custom exercises',
            code: customExercisesError.code ?? 'UNKNOWN',
            details: customExercisesError.message ?? customExercisesError.hint ?? null,
          }),
          { status: 500, headers: { ...cors, 'Content-Type': 'application/json' } }
        );
      }

      const customExercisesPage = ((customExercises ?? []) as Record<string, unknown>[]);
      if (customExercisesPage.length > remainingPageSize) {
        hasMore = true;
        const lastCustomExercise = customExercisesPage[remainingPageSize - 1];
        const updatedAtMs = new Date(lastCustomExercise.updated_at as string).getTime();
        nextCursor = encodeCursor('customExercises', updatedAtMs, lastCustomExercise.id as string);
        customExercisesPage.splice(remainingPageSize);
      }

      customExerciseDtos = customExercisesPage.map((ce: Record<string, unknown>) => ({
        clientId: ce.id,
        name: ce.name,
        displayName: ce.display_name,
        muscleGroup: ce.muscle_group,
        equipment: Array.isArray(ce.equipment) ? ce.equipment.join(",") : "",
        defaultCableConfig: ce.default_cable_config,
      }));
      remainingPageSize -= customExerciseDtos.length;
    }

    // =========================================================================
    // 7. Return paginated response with cursor metadata
    // =========================================================================
    const response = {
      syncTime,
      // Pagination metadata (optional for backward compatibility)
      nextCursor: nextCursor ?? undefined,
      hasMore,
      // Entity data
      sessions: sessionDtos,
      routines: routineDtos,
      cycles: cycleDtos,
      personalRecords: personalRecordDtos,
      rpgAttributes: rpgDto,
      badges: badgeDtos,
      gamificationStats: gamificationDto,
      localProfiles: localProfiles,
      externalActivities: externalActivityDtos,
      customExercises: customExerciseDtos,
      ...(profilePreferenceSections === undefined
        ? {}
        : { profilePreferenceSections }),
    };

    console.log('[PULL] Response:', {
      sessions: sessionDtos.length,
      routines: routineDtos.length,
      cycles: cycleDtos.length,
      badges: badgeDtos.length,
      hasMore,
    });

    return new Response(JSON.stringify(response), {
      headers: { ...cors, 'Content-Type': 'application/json' },
    });
  } catch (err) {
    console.error('mobile-sync-pull error:', err);
    return new Response(
      JSON.stringify({ error: 'Internal server error' }),
      { status: 500, headers: { ...cors, 'Content-Type': 'application/json' } }
    );
  }
}

export function createMobileSyncPullHandler(
  dependencies: MobileSyncPullHandlerDependencies = defaultMobileSyncPullDependencies(),
): (req: Request) => Promise<Response> {
  return (req) => mobileSyncPullHandler(req, dependencies);
}

if (import.meta.main) {
  Deno.serve(createMobileSyncPullHandler());
}
